trigger:
  - master

jobs:

- job: 'tests'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 2

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install -r requirements.txt
        python -m pip install -e exercises -e solutions
      displayName: "Installation"

    - script: |
        python -m tmclass_exercises.data_download
        python -m tmclass_solutions.data_download
      displayName: "Download auxiliary data and models"

    - script: |
        python -m pytest -vv -l exercises --junitxml=test-exercises-results.xml
      displayName: "Pytest exercises"

    - script: |
        python -m pytest -vv -l solutions --junitxml=test-solutions-results.xml
      displayName: "Pytest solutions"

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Python $(python.version)'
      condition: succeededOrFailed()

- job: 'flake8'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        python -m pip install flake8
        python -m flake8
      displayName: 'Code and style checks (flake8)'
      condition: succeededOrFailed()
