name: tmclass
dependencies:
  - pip:
      - matplotlib  # use pip to install matplotlib to skip the qt dependency
  - lxml
  - cssselect
  - selenium
  - ipython
  - jupyterlab
  - scikit-learn
  - pandas
  - pyarrow
  - pytest
  - flake8
